server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: Gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/auth/**

            - id: popup-space-history-service
              uri: ${POPUP_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/spaces/*/popups/history

            - id: popup-user-history-service
              uri: ${POPUP_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/users/*/popups/history

            - id: user-service
              uri: ${USER_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/users/**

            - id: space-service
              uri: ${SPACE_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/spaces/**

            - id: matching-service
              uri: ${MATCHING_SERVICE_URL:http://localhost:8083}
              predicates:
                - Path=/matchings/**

            - id: popup-service
              uri: ${POPUP_SERVICE_URL:http://localhost:8086}
              predicates:
                - Path=/popups/**

            - id: alarm-service
              uri: ${ALARM_SERVICE_URL:http://localhost:8085}
              predicates:
                - Path=/alarm/**

            - id: admin-service
              uri: ${ADMIN_SERVICE_URL:http://localhost:8087}
              predicates:
                - Path=/admin/**

            - id: image-service
              uri: ${IMAGE_SERVICE_URL:http://localhost:8084}
              predicates:
                - Path=/images/**

            - id: chating-service
              uri: ${CHATING_SERVICE_URL:http://localhost:8089}
              predicates:
                - Path=/chat/**

            - id: chating-websocket-service
              uri: ${CHATING_WS_SERVICE_URL:ws://localhost:8089}
              predicates:
                - Path=/ws/chat
